# Generated by Django 5.0.1 on 2024-02-07 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='Date'),
        ),
    ]
